---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - pre-release
  push:
    branches:
      - main
      - pre-release
      - 266_fail_on_r_cmd_check_notes
  workflow_dispatch:

jobs:
  # audit:
  #   name: Audit Dependencies 🕵️‍♂️
  #   uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@main
  r-cmd:
    name: R CMD Check 🧬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@266_fail_on_r_cmd_check_notes
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      check-note-blocklist: true
      note-blocklist: |
        checking package dependencies ... NOTE( )+Depends: includes the non-default packages
        checking R code for possible problems ... NOTE( )+.*: no visible global function definition for
        checking for unstated dependencies in vignettes ... NOTE( )+\'.*\' import not declared from
        checking dependencies in R code ... NOTE( )+Namespace in Imports field not imported from
        checking installed package size ... NOTE( )+installed size is





  # coverage:
  #   if: github.event_name == 'pull_request'
  #   name: Coverage 📔
  #   uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # linter:
  #   if: github.event_name == 'pull_request'
  #   name: SuperLinter 🦸‍♀️
  #   uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@main
  # roxygen:
  #   name: Roxygen 🅾
  #   uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # gitleaks:
  #   name: gitleaks 💧
  #   uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@main
  # spelling:
  #   if: github.event_name == 'pull_request'
  #   name: Spell Check 🆎
  #   uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
  # links:
  #   if: github.event_name == 'pull_request'
  #   name: Check URLs 🌐
  #   uses: insightsengineering/r.pkg.template/.github/workflows/links.yaml@main
  # vbump:
  #   name: Version Bump 🤜🤛
  #   if: github.event_name == 'push'
  #   uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # version:
  #   name: Version Check 🏁
  #   uses: insightsengineering/r.pkg.template/.github/workflows/version.yaml@main
  # licenses:
  #   name: License Check 🃏
  #   uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@main
  # style:
  #   if: github.event_name == 'pull_request'
  #   name: Style Check 👗
  #   uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@main
